version: '3'
services:
    app:
        build:
            context: docker/app
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./docker/app/php/Z-custom.ini:/usr/local/etc/php/conf.d/Z-custom.ini
            - ./docker/app/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./src:/var/www/html
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=p1ssw0rd
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=p1ssw0rd
        user: "${UID_GID}"
    cache:
        image: redis:6.2
        ports:
            - "6379:6379"
        volumes:
            - ./docker/cache/conf:/usr/local/etc/redis
            - ./docker/cache/data:/data
        command: redis-server /usr/local/etc/redis/redis.conf --save 60 1            
